version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      #      - ./database/mysql-data:/var/lib/mysql # Guardar Backup de Database
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./database/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
    networks:
      - app-network


  backend:
    build:
      context: ./trading-webapp-backend
      dockerfile: Dockerfile
    container_name: backend-container
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/trading_db?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: ["dockerize", "-wait", "tcp://mysql-container:3306", "-timeout", "90s", "java", "-jar", "/app/trading-webapp-backend-0.0.1-SNAPSHOT.jar"]



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-container
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge