CREATE DATABASE IF NOT EXISTS trading_db;

USE trading_db;

-- Tabela Users
CREATE TABLE IF NOT EXISTS Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabela Type_Assets
CREATE TABLE IF NOT EXISTS Type_Assets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabela Assets
CREATE TABLE IF NOT EXISTS Assets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  symbol VARCHAR(255) UNIQUE NOT NULL,
  type_id INT NOT NULL,
  price DECIMAL(10,2) DEFAULT 0.00 NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (type_id) REFERENCES Type_Assets(id)
);

-- Tabela Type_Trades
CREATE TABLE IF NOT EXISTS Type_Trades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabela Trades
CREATE TABLE IF NOT EXISTS Trades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  asset_id INT NOT NULL,
  trade_type_id INT NOT NULL,
  quantity DECIMAL(10,2) NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id),
  FOREIGN KEY (asset_id) REFERENCES Assets(id),
  FOREIGN KEY (trade_type_id) REFERENCES Type_Trades(id)
);

-- Tabela Wallets
CREATE TABLE IF NOT EXISTS Wallets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNIQUE NOT NULL,
  balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id)
);

-- Tabela StockHistory
CREATE TABLE IF NOT EXISTS StockHistory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  asset_id INT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (asset_id) REFERENCES Assets(id)
);
